version: '3'

services:
  # backend:
  #   container_name: techsocial_backend
  #   image: techsocial_backend:dev
  #   build:
  #     context: .
  #     target: development
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules

  techsocialdb:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ./temp/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=techsocial
      - POSTGRES_PASSWORD=adminadmin

networks:
  techsocial:
