version: '3'
services:
  database:
    image: 'postgres:alpine'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./temp/data/postgres/:/var/lib/postgresql/data/
    networks:
      - techsocial

networks:
  techsocial:
